### ISSUE TITLE
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.0Q1uxf)

### ISSUE THREAD

**Issue by pietrondo** [social-manager-tools/socialmanagertools-gui#69]
### Versions

Replace the values below with your own:

- **Social Manager Tools Version:** v0.6.5
- **Social Platform:** Instagram
- **Operating System:** debian stretch

This is my console log!
```
  ~ social-manager-tools 
(node:15037) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.0Q1uxf)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Social Manager Tools/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/opt/Social Manager Tools/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:190:3)
(node:15037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[15460:15460:0624/105849.994975:ERROR:browser_dm_token_storage_linux.cc(101)] Error: /etc/machine-id contains 0 characters (32 were expected).
[15492:15492:0624/105850.255502:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.
[15460:15524:0624/105850.284878:ERROR:token_service_table.cc(141)] Failed to decrypt token for service AccountId-104820464767286904100
[15460:15487:0624/105850.382080:ERROR:gcm_store_impl.cc(930)] Failed to restore security token.
[15460:15460:0624/105850.758555:ERROR:account_tracker.cc(240)] AccessTokenFetched error: Invalid credentials (credentials missing).
[15460:15460:0624/105850.758638:ERROR:account_info_fetcher.cc(59)] OnGetTokenFailure: Invalid credentials (credentials missing).
[15460:15478:0624/105851.147714:ERROR:mcs_client.cc(707)] Failed to log in to GCM, resetting connection.
[15460:15460:0624/105852.295134:ERROR:data_type_manager_impl.cc(38)] Passwords cryptographer error was encountered: 
[15460:15460:0624/105854.761323:ERROR:http_bridge.cc(110)] Not implemented reached in virtual void syncer::HttpBridgeFactory::OnSignalReceived()
[15460:15478:0624/105901.888448:ERROR:browser_process_sub_thread.cc(221)] Waited 6813 ms for network service

```

**Comment by ptkdev** [comment]
Install chromium on your system (`apt-get install chromium`) and set path of chromium in `config.js`, example: `/usr/bin/chromium-browser`

**Comment by ptkdev** [comment]
Electron bug: [#18182](https://github.com/electron/electron/issues/18181)

**Comment by ptkdev** [comment]
Possible workaround: downgrade _electron_ to **v2.0.0** in `package.json`

**Comment by pietrondo** [comment]
i don't find electron in package.json..

**Comment by ptkdev** [comment]
@pietrondo [line 64](https://github.com/social-manager-tools/socialmanagertools-gui/blob/nightly/package.json)

**Comment by pietrondo** [comment]
Error 
[https://termbin.com/ktcx](https://termbin.com/ktcx)
